### PR TITLE
Added GitHub Buttons to Fix #42

### LINKED ISSUE #42: Add github star/watch buttons
Found these [neat github buttons](https://ghbtns.com/). I think we should try and get some use out of them, they are a bit nicer than the normal ~~bootstrap~~ skeleton button we have right now. Although, because they have different purposes maybe we should have them co-exist... Except I have no idea where we would put them.

### PR DESCRIPTION
**Pull request by rafej**
Hey Everyone,
I added the new GitHub buttons addressed in #42  just under the 'Contribute to GitHub' button.
Rafe

### CODE REVIEW

**Comment by paked** [comment]
Ok, this is what they look like on firefox: https://www.dropbox.com/s/e40chnjgdw8c1sz/Screenshot%202015-07-26%2010.42.43.png?dl=0

Maybe they should be in the smaller size?

**Comment by rodrigoargumedo** [comment]
Can you rebase and squash those extra commits via CLI?

**Comment by paked** [comment]
For the sake of @rafej doing it himself (as a learning experience), I made this little gif on how to squash commits.

git_rebase

**Comment by paked** [comment]
It is important to note, that after you have made those changes you will need to `git push -f

**Comment by paked** [comment]
hang on... why is my commit in there?

**Comment by paked** [comment]
apart from that LGTM :+1:....

**Comment by KevinPayravi** [comment]
Great, thanks guys! I could learn a thing or two from that commit squashing.

**Comment by paked** [comment]
Congratulations @rafej :)

**Pull request merged**
