### PR TITLE
Added DeltaHacks

### PR DESCRIPTION
**Pull request by yenvanio**

### CODE REVIEW

**Comment by paked** [comment]
@yenvanio: Can you please fix the error on your last commit. (Namely: `HackDavis should be before DeltaHacks`)

**Comment by yenvanio** [comment]
I fixed it, thank you

**Comment by paked** [comment]
@yenvanio: Did you push your changes? I can't see them here.

**Comment by jkdf2** [comment]
This should be closed since it was added in a different PR.

**Comment by paked** [comment]
@jkdf2: Thanks for pointing that out!

**Pull request closed without merging**
