### PR TITLE
Hack in the north dates changed

### PR DESCRIPTION
**Pull request by adeora7**
Changing the dates of HackintheNorth, IIIT-Allahabad, India

- Member of the organising team.

### CODE REVIEW

**Comment by adeora7** [comment]
@KevinPayravi  Please accept the changes. It is misleading right now.

**Comment by paked** [comment]
@adeora7: Sorry this took so long!

**Comment by adeora7** [comment]
Thanks

**Comment by KevinPayravi** [comment]
Echoing the apologies - been out of town all week :) Thanks all.

**Pull request merged**
