### PR TITLE
Site Redesign

### LINKED ISSUE #82: Website Redesign
Skeleton's great, but it's not really necessary for this project. I'll work on custom styling over Thanksgiving Break.

### PR DESCRIPTION
**Pull request by rodrigoargumedo**
Closes #82 

(This is still work in progress, don't merge it just yet until I say it is ready to do so.)

### CODE REVIEW

**Comment by paked** [comment]
I don't think this is that relevant to the API

**Comment by rodrigoargumedo** [comment]
Thanks for the heads up. My bad.

**Comment by paked** [comment]
@rodrigoargumedo Have we got a status update on this?

**Comment by rodrigoargumedo** [comment]
Closing the request until we have a grasp idea of how we can work on it.

**Pull request closed without merging**
