### PR TITLE
Add Chi Hacks #2 fixed

### PR DESCRIPTION
**Pull request by avisaxena33**

### CODE REVIEW

**Comment by KevinPayravi** [comment]
Good progress, thanks Aviral! Just two more minor things:

* `Chicago, IL United States` -> `Chicago, IL, United States`
* `"travel": "no ",` -> `"travel": "no",`

Once those are fixed, I think everything should be good to go.

**Comment by avisaxena33** [comment]
@KevinPayravi  Done and done

**Comment by rodrigoargumedo** [comment]
The reason why the build was failing was the 04.json was blank but I will make some reverting changes and add the missing details.

**Comment by rodrigoargumedo** [comment]
Closing since it is now merged.

**Comment by KevinPayravi** [comment]
Good call, thanks @rodrigoargumedo - and thank you @avisaxena33!

**Pull request closed without merging**
