### PR TITLE
Added length to Virtual2Reality which crashed parser

### PR DESCRIPTION
**Pull request by bholagabbar**
Please try and keep the data consistent, our parser crashed due to this.

### CODE REVIEW

**Comment by KevinPayravi** [comment]
@bholagabbar Sorry about that, looks like we missed it. Thank you!

**Comment by bholagabbar** [comment]
@KevinPayravi Can we include tests in TravisCI that check whether the current month's hackathons have all the fields included? Something like that?

**Comment by paked** [comment]
We have a basic test.js which does *some* of that. I'd be happy to review
any PRs which build on it :)

**Comment by bholagabbar** [comment]
@paked Sounds good, I'll give it a shot. This is the test file right? https://github.com/Hackalist/Hackalist.github.io/blob/master/test.js

**Comment by paked** [comment]
Yup. It isn't much :p

**Comment by bholagabbar** [comment]
Haha yeah. Just asserting whether all fields exist or not should be fine. I'll take a look later this evening maybe. I had been breaking my head all day yesterday over why our API wouldn't return requests and turns out it was because of this very issue. Hopefully it works now since we've fixed this.

**Pull request merged**
