### PR TITLE
Fix toggling issues

### PR DESCRIPTION
**Pull request by paked**
For #33.

Wow I killed my git history...

### CODE REVIEW

**Comment by paked** [comment]
Also, feel free to check out the live demo at: http://harrisonshoebridge.me/Hackalist.github.io

**Comment by KevinPayravi** [comment]
Hmm...looks great except the prizes toggle, which seems to not work or is backwards (not sure why yet).

**Comment by paked** [comment]
Ok. I will fix that ahaha sorry

**Comment by paked** [comment]
@KevinPayravi Ok fixed, sorry for the delay. I think I'm going to try and revert to the old toggle style, would you prefer that in a separate PR

**Comment by KevinPayravi** [comment]
Perfect, thanks for the quick fix! No need to apologize. I've merged your commits, but feel free to change the toggle style.

**Pull request merged**
