### PR TITLE
Merge pull request #2 from Hackalist/master

### PR DESCRIPTION
**Pull request by daphnechen**
get latest

### CODE REVIEW

**Comment by KevinPayravi** [comment]
Hi Daphne - I see no changes made with this Pull Request. Did you mean to submit something?

**Comment by daphnechen** [comment]
My bad -- fixed now!

**Comment by KevinPayravi** [comment]
Great, thank you @daphnechen! To make finding hackathons easier for our users, could you also make another commit and add to the 'notes' field that this is an all-women hackathon?

**Comment by daphnechen** [comment]
Added the note!

**Comment by KevinPayravi** [comment]
Thanks @daphnechen! It's now live on the site :)

**Pull request merged**
