### PR TITLE
added Output vs Output New Delhi, India

### PR DESCRIPTION
**Pull request by architv**

### CODE REVIEW

**Comment by rodrigoargumedo** [comment]
Thanks! @architv

**Comment by architv** [comment]
Thanks for the API! @rodrigoargumedo

**Comment by rodrigoargumedo** [comment]
You are absolutely welcome!

cc: @KevinPayravi (owner) and @Hackalist/team-hackalist-github-io

**Comment by KevinPayravi** [comment]
<3

**Comment by paked** [comment]
:heart:

**Pull request merged**
