### PR TITLE
Add McKinsey Analytics Online Hackathon

### PR DESCRIPTION
**Pull request by bunnymaingi**
The Hackathon is being hosted on AnalyticsVidhya.com

### CODE REVIEW

**Comment by rodrigoargumedo** [comment]
Hi @bunnymaingi - please take a look at our instructions and examples for how to list a hackathon, and let us know if you have any questions.

https://github.com/Hackalist/Hackalist.github.io#api

**Comment by bunnymaingi** [comment]
Hi @rodrigoargumedo I have tried to replicate the instructions as given on your site but could you please specify what is the missing parameter or the appropriate way to list. Should be really helpful.

**Comment by rodrigoargumedo** [comment]
Check your test logs before I merge your awesome commits. Link to the log: https://travis-ci.org/Hackalist/Hackalist.github.io/builds/349663331?utm_source=github_status&utm_medium=notification

**Comment by bunnymaingi** [comment]
Changes made according to the required format.
Thanks for helping. Please merge my commits.

**Pull request merged**
